// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwZ83oFYKbbZlUk4uF-fUrRYEN_OfszvU',
    appId: '1:1067819382948:web:b58061bf4377ca5363ce31',
    messagingSenderId: '1067819382948',
    projectId: 'schedulepro-37685',
    authDomain: 'schedulepro-37685.firebaseapp.com',
    storageBucket: 'schedulepro-37685.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3sW3RXsiveHcE7Dc7TJdodTFk9d2Z1i0',
    appId: '1:1067819382948:android:ba9831cf028be88463ce31',
    messagingSenderId: '1067819382948',
    projectId: 'schedulepro-37685',
    storageBucket: 'schedulepro-37685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiopQ2YTGghaZJ542FV7xVrwYooXyDXLY',
    appId: '1:1067819382948:ios:339027736811856d63ce31',
    messagingSenderId: '1067819382948',
    projectId: 'schedulepro-37685',
    storageBucket: 'schedulepro-37685.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiopQ2YTGghaZJ542FV7xVrwYooXyDXLY',
    appId: '1:1067819382948:ios:339027736811856d63ce31',
    messagingSenderId: '1067819382948',
    projectId: 'schedulepro-37685',
    storageBucket: 'schedulepro-37685.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwZ83oFYKbbZlUk4uF-fUrRYEN_OfszvU',
    appId: '1:1067819382948:web:d51f42791641849663ce31',
    messagingSenderId: '1067819382948',
    projectId: 'schedulepro-37685',
    authDomain: 'schedulepro-37685.firebaseapp.com',
    storageBucket: 'schedulepro-37685.firebasestorage.app',
  );
}
